# Конфигурационных файл для программы VKPrikol
# Инструкция по использованию находится в README.md

[VK]
login =
password =

[Aim]
group_id =
album_id =

[Settings]
UploadLimit = 1
FolderWithPhotos = test
AutoCheckForUpdates = yes

[Info]
Version = 1.0
PythonVersion = 3.7